[project]
name = "async-thread-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "requests>=2.32.5",
    "starlette>=0.52.1",
    "uvicorn>=0.40.0",
]
